Add Simplified Chinese Support
EduMIPS64/edumips64 pull request #772
Opened 2023-09-07 09:09 UTC by smallg0at

This pull request add Simplified Chinese as a language option. 

The docs haven't been translated, and will redirect to the English version.

2023-09-07 10:38 UTC, smallg0at commented
Something's going wrong with the code analysis here...

2023-09-07 11:56 UTC, lupino3 commented
Hi @smallg0at, and thanks for your contribution! I kicked off the CI pipelines, since PR by non-owners by default do not trigger them.

Codacy checks are failing because your changes trigger some tests that were anyway failing: https://app.codacy.com/gh/EduMIPS64/edumips64/pullRequest?prid=12573761. We'll see if I can just bypass it. Let's see if the other build and test pipelines succeed.

I'll be happy to assist you in getting this PR merged and releasing a new version with Simplified Chinese translation, thanks a lot for your work!

2023-09-07 12:14 UTC, lupino3 requested changes
I think we need to fix one constant to make it compile. I provided suggestions, please accept them if they are correct. Thanks!

2023-09-07 12:14 UTC, lupino3 commented on src/test/java/org/edumips64/CliRunnerTest.java
> +        Locale.setDefault(Locale.SCHINESE);
```suggestion
        Locale.setDefault(Locale.SIMPLIFIED_CHINESE);
```

I think this should be `SIMPLIFIED_CHINESE`?
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Locale.html#SIMPLIFIED_CHINESE

2023-09-07 12:14 UTC, lupino3 commented on src/test/java/org/edumips64/CliRunnerTest.java
> +        Locale.setDefault(Locale.SCHINESE);
```suggestion
        Locale.setDefault(Locale.SIMPLIFIED_CHINESE);
```

Same here, I think.

2023-09-07 13:34 UTC, smallg0at commented
I'm seeing this font fallback issue here

![image](https://github.com/EduMIPS64/edumips64/assets/30719670/492c08fe-4d3f-492e-be7d-b748f5c643b3)

2023-09-07 14:08 UTC, lupino3 commented
> I'm seeing this font fallback issue here. For some reason it doesn't fallback properly, and I am unable to fix :(
> 
> ![image](https://user-images.githubusercontent.com/30719670/266333733-492c08fe-4d3f-492e-be7d-b748f5c643b3.png)

I'll have a look at this as soon as possible!

2023-09-09 16:52 UTC, lupino3 commented
Ok, I think I am able to reproduce the error:

<img width="657" alt="image" src="https://github.com/EduMIPS64/edumips64/assets/200139/feffcc5c-8f6c-4c62-b66a-f6774692630b">

FWIW, I had to add the following line to `build.gradle.kts`, otherwise it would not compile on my Windows machine:

<img width="231" alt="image" src="https://github.com/EduMIPS64/edumips64/assets/200139/a811f13b-a5fe-40c5-b919-ef832ca79c47">

2023-09-09 17:13 UTC, lupino3 commented
Ok, I found the problem. We are explicitly setting the Verdana font in `ErrorDialog`, which cannot display Chinese characters, apparently. Removing the explicit font setting fixes the issue:

<img width="537" alt="image" src="https://github.com/EduMIPS64/edumips64/assets/200139/71e65479-aef7-4db9-9373-28029995626a">

<img width="516" alt="image" src="https://github.com/EduMIPS64/edumips64/assets/200139/e7e8efcc-cde4-44d5-9be0-3a2bd9ef24f3">

This is only a work-around though. We need to manage fonts more consistently in the app.

I'll see if I can think about how to do it tomorrow, so I can unblock your PR, @smallg0at

2023-09-10 07:32 UTC, lupino3 commented
Hi @smallg0at, I just merged #776, which should fix the errors that caused you problems.

Could you please rebase your changes on top of the new `master` branch?

Then your PR should be good to go.
Let me know if you need any help, and thanks for your contribution!

Once your change is merged, I'll release a new EduMIPS64 version, so you can get the Simplified Chinese version from official packages.

2023-09-12 04:36 UTC, smallg0at commented
I'm currently working on translating the docs, so it might take some extra days to complete

2023-09-12 07:46 UTC, lupino3 commented
Thank you very much, @smallg0at! Appreciate your initiative and effort. Will wait for your work to be finished!

2023-09-12 15:58 UTC, smallg0at commented
The translation work is complete, though it still has the following problems:
- Due to the use of machine translation (DeepL), many warnings will appear.
- Chinese docs PDF currently fail to build and will produce empty file

```
         [ERROR] pdfbuilder.py:161 Failed to build doc
         Traceback (most recent call last):
         Traceback (most recent call last):FAILED
           File "D:\Code\edumips64\.gradle\python\Lib\site-packages\rst2pdf\pdfbuilder.py", line 158, in write
             docwriter.write(doctree, destination)
           File "D:\Code\edumips64\.gradle\python\Lib\site-packages\docutils\writers\__init__.py", line 80, in write
             self.translate()
           File "D:\Code\edumips64\.gradle\python\Lib\site-packages\rst2pdf\pdfbuilder.py", line 621, in translate
             contents[0] += nodes.Text(langmod.labels['contents'])
                                       ^^^^^^^^^^^^^^
         AttributeError: module 'zh' has no attribute 'labels'
```

2023-09-13 13:11 UTC, lupino3 commented
It seems to be building correctly in Github Actions.

2023-09-13 16:07 UTC, smallg0at commented
> <img alt="image" width="1645" src="https://user-images.githubusercontent.com/200139/267670987-181aef4b-8c9f-403d-a386-1ffbcd7cfb81.png">
> in-application help works, but it doesn't render well for me

Oops. UTF-8 mysteriously displayed with Windows 1252 encoding. Have no idea what's going on.

> It seems to be building correctly in Github Actions.

Error can be seen [here](https://github.com/EduMIPS64/edumips64/actions/runs/6161815633/job/16753949314#step:10:392)

2023-09-13 16:16 UTC, smallg0at commented
Also the actions will need to be updated later for Chinese docs pdf uploading

2023-09-13 19:36 UTC, lupino3 commented
I fixed the PDF build (we needed to have the right language code for Simplified Chinese in Sphinx), but now the PDF only displays black boxes. Need to investigate a bit more.

2023-09-13 19:55 UTC, lupino3 commented
We might have a problem with PDF production.. it looks like the library we are using (rst2pdf) may not support simplified chinese output: https://github.com/rst2pdf/rst2pdf/issues/1075. Need to investigate more.

2023-09-13 20:33 UTC, lupino3 commented
Found a Docker image claiming to be `rst2pdf` set up to output Korean PDF. So I think it is a matter of configuration rather than `rst2pdf` not supporting Chinese fonts.

2023-09-13 20:54 UTC, lupino3 commented
@smallg0at I tried to copy what's here: https://github.com/S4Plus/ABC/blob/master/toolbox/rst2pdf.md

It still doesn't work for me. Could you please read the page and try to see what I'm doing wrong? Thanks!

2023-09-13 20:57 UTC, lupino3 commented
It has to be possible, because this PDF looks like it's built with rst2pdf: https://buildmedia.readthedocs.org/media/pdf/test23/1.3.3/test23.pdf

2023-09-14 06:10 UTC, smallg0at commented
Now Sarasa Gothic is bundled instead of Simsun to (i) prevent font licensing issues (ii) improve how the manual looks (as Simsun looks terrible on screen). Unfortunately, it still do not work.

2023-09-14 06:37 UTC, smallg0at commented
After hours of tinkering I give up. Will try replacing the rst -> pdf chain to [rinohtype](https://github.com/brechtm/rinohtype).

2023-09-16 15:05 UTC, smallg0at commented
> After hours of tinkering I give up. Will try replacing the rst -> pdf chain to [rinohtype](https://github.com/brechtm/rinohtype).
> 
> May also allow TeX to return after exiled from this project 12 years ago, if that also didn't work.

Rinohtype attempt failed, and the code can be seen [here](https://github.com/smallg0at/edumips64/tree/rinohtype_attempt).

Chinese PDF exporting support will be dropped for now, and when [this](https://github.com/EduMIPS64/edumips64/pull/772#issuecomment-1717648202) issue got fixed this pull request should be ready for merge.

2023-09-17 09:48 UTC, lupino3 commented
Thanks, I'll see if I can have a look into the rendering issue today.

2023-09-17 18:18 UTC, lupino3 commented
https://docs.oracle.com/cd/E19253-01/819-0913/819-0913.pdf Javahelp docs. (for future reference)

2023-09-17 19:12 UTC, lupino3 commented
Found this tool which has Russian help working with Javahelp, might be able to see how the localization works: https://github.com/logisim-evolution/logisim-evolution.

2023-09-17 20:39 UTC, lupino3 commented
Just some updates: still not working. I tried using the `SansSerif` font family - since the help was using `Dialog`, with no luck. Also tried adding `xml:lang='zh'` to the help files. Still no luck.

I would suggest merging the PR with the help redirecting to the English manual, just to close the main localization feature, and open an issue for Simplified Chinese in-app help and PDF manual.

What do you think, @smallg0at?

2023-09-18 00:20 UTC, smallg0at commented
The help system works for the main audience of this language anyway. I'll check the logisim-evolution implementation and if it doesn't work, put up a warning within the Chinese docs to tell the user what's going on.

2023-09-18 01:15 UTC, smallg0at commented
Tested in windows sandbox + English (UK) / Italian (Italy) locale settings. I assume that it's some issue lying in the compile workflow, as no matter what language I'm in the setup always use Chinese. @lupino3 could you trigger the CI action once so that I can see how the GitHub actions build behaves?

2023-09-18 01:34 UTC, smallg0at commented
Also this codacy check is ridiculous. Why is this only-repeated-twice string a problem?

2023-09-18 12:09 UTC, lupino3 commented
> Tested in windows sandbox + English (UK) / Italian (Italy) locale settings, the packages that I built does not have this issue. I assume that it's some issue lying in the compile workflow, as even windows sandbox defaults to english, the setup always use Chinese. @lupino3 could you trigger the CI action once so that I can see how the GitHub actions build behaves?

CI triggered. Note that the language is not inferred from the locale set in environment variables, and instead they are persisted in the user preferences store.

2023-09-18 12:47 UTC, smallg0at commented
<img width="547" alt="image" src="https://github.com/EduMIPS64/edumips64/assets/30719670/5b1bc35e-e241-4e67-82e7-951514b95dc3">

Didn't expect that...

2023-09-18 15:26 UTC, smallg0at commented
> > Tested in windows sandbox + English (UK) / Italian (Italy) locale settings, the packages that I built does not have this issue. I assume that it's some issue lying in the compile workflow, as even windows sandbox defaults to english, the setup always use Chinese. @lupino3 could you trigger the CI action once so that I can see how the GitHub actions build behaves?
> 
> CI triggered. Note that the language is not inferred from the locale set in environment variables, and instead they are persisted in the user preferences store.

Actually, Windows sandbox will only inherit the environment locale option (from the physical machine), the user preference language settings will always be en_US initially. The language of the installer does depend on the locale of the computer building it, as seen here:

![image](https://github.com/EduMIPS64/edumips64/assets/30719670/81265fc5-296e-4851-8ed5-f6deaa3ac682)

The one on the top is from GitHub release (1.2.10).

2023-09-19 12:13 UTC, lupino3 commented
Thanks @smallg0at. I had tried the same fix here a few days ago (https://github.com/EduMIPS64/edumips64/pull/777/commits/f32f1ff73f59917bcfe3fdb383deef750c54fe86) but it didn't seem to work :/

2023-09-19 15:54 UTC, smallg0at commented
Good news: it has been confirmed fixed.

2023-09-19 16:02 UTC, smallg0at commented
There is some hope for rst2pdf however. Logs shows that it cannot locate the stylesheet files, which may be crucial for the implementation. 

![image](https://github.com/EduMIPS64/edumips64/assets/30719670/f86e6e4b-0097-4927-b904-6906473df291)

2023-09-19 16:05 UTC, smallg0at commented
Seems to need a token for Webapp distribution to work

https://github.com/smallg0at/edumips64/actions/runs/6237968146/job/16932897585#step:9:23

2023-09-19 16:06 UTC, lupino3 commented
Thanks for the `read-properties` fix, I'm actually merging it separately here once I see it works: https://github.com/EduMIPS64/edumips64/pull/777 (I'll credit you in the PR)

2023-09-19 16:38 UTC, smallg0at commented
![image](https://github.com/EduMIPS64/edumips64/assets/30719670/169f7a77-c0d7-40a9-b295-2ffba36f1af7)

Found this issue, but in GBK this time. According to my findings this is probably what happened: 

- When changing locale, JDK will automatically change the encoding that it's running on. While it defaults to utf-8 in chinese when installed, the other languages do not get this treatment. HOWEVER, when changing locale to Chinese (China), it will instead modify the settings to be GBK, which adds up another level of mess.
- When loading up a help file, `javax.help.HelpBroker` will NOT respect the HTML encoding and will use the default system-wide java encoding.

2023-09-19 16:46 UTC, smallg0at commented
> Found this tool which has Russian help working with Javahelp, might be able to see how the localization works: https://github.com/logisim-evolution/logisim-evolution.

This project use `JHelp` and the implementation can be seen in `src\main\java\com\cburch\logisim\gui\menu\MenuHelp.java`. I can't really code Java so I'm unable to help.

2023-09-20 03:01 UTC, smallg0at commented
@lupino3 Let's give it one last try to at least allow the release MSI has normal working Chinese docs. Please set your system variable `JAVA_TOOL_OPTIONS` to `-Dfile.encoding=UTF8`, then build the msi and test it. If it doesn't work, I'll give up and use the English one.

2023-09-21 08:58 UTC, lupino3 commented
It works!
<img width="906" alt="image" src="https://github.com/EduMIPS64/edumips64/assets/200139/2c082eff-fa3f-4972-9313-d90db97b5379">
The environment variable was picked up by Gradle correctly, it echoed it during the build process.

I wonder if we can just set it in the Gradle file and have it work for all types of build?

2023-09-21 11:31 UTC, lupino3 commented
Ok, I verified that it doesn't seem to matter how it's built, but that option needs to be set as an environment variable when the JAR is executed. Let's see if we can work around it.

2023-09-21 11:38 UTC, lupino3 commented
I'm pretty sure the MSI works because we already pass `-Dfile.encoding=utf-8` to the `java` command line that we build for the Windows shortcut:

<img width="944" alt="image" src="https://github.com/EduMIPS64/edumips64/assets/200139/4caa6fe4-7fa7-4f04-b429-41f276791108">

What we can do is to add this option to the Ubuntu package as well and add a warning at the top of the Chinese docs saying (in English) to load the JAR with `-Dfile.encoding=utf-8` if the help looks garbled.

According to https://stackoverflow.com/questions/361975/setting-the-default-java-character-encoding, there is no way of setting this option within the source code, as it's something used during initialization.

2023-09-21 12:47 UTC, smallg0at commented
Thanks for testing. I'll do the following things and then it will be ready to merge:
- [ ] Create Issue: In-app documentation does not respect document encoding
- [ ] Create Issue: CJK characters won't render correctly in the PDF help file
- [ ] Edit docs: add an image in both Chinese and English to state what's happening

2023-09-21 14:15 UTC, smallg0at commented
This pull request is ready for merging, as long as Codacy don't do anything funny.

2023-09-21 16:40 UTC, merged

2023-09-21 16:42 UTC, lupino3 commented
Thanks for your contribution here @smallg0at! I'll see if I can take a look at the issues you filed in the next days, and then I'll create a new release with Simplified Chinese support!