Add: darkmode support
EduMIPS64/edumips64 pull request #802
Opened 2023-10-09 09:48 UTC by smallg0at

![image](https://github.com/EduMIPS64/edumips64/assets/30719670/def9bfb0-2ed0-4b38-b162-4807534a291c)

![image](https://github.com/EduMIPS64/edumips64/assets/30719670/b50da112-9291-45b7-b4e2-ac2400f4698f)

This adds darkmode support and closes #796 

Feature introduced:
- A toggle to enable dark mode, which take effect on restart

Problems still existing:
- Default highlight colors are way too bright, lacking any contrast with the text wrapped by it. Current solution resolves some of the issue but the UI design here should be further discussed
- Loading up a file after theme change in settings will cause the theme of Cycles and Pipeline window to misalign with the main window

2023-10-09 10:33 UTC, smallg0at commented
![image](https://github.com/EduMIPS64/edumips64/assets/30719670/c485be71-bb0b-425d-8539-dc342f6bffca)

This seems optimal, though user preference is somewhat ignored as it uses darker() three times

2023-10-09 17:03 UTC, smallg0at commented
![image](https://github.com/EduMIPS64/edumips64/assets/30719670/90acd018-ba33-4aea-9847-225e2682d7f3)

Icons have been redesigned from the ground up for better presentation & to adapt to dark mode

2023-10-11 13:03 UTC, lupino3 commented
Thanks for your work on this PR! I want to release version 1.3, because we radically changed the semantics of `DMULU` and there are other fixes, but I'll wait to see if we can get dark mode in as well. Thanks!

2023-10-11 13:05 UTC, lupino3 commented
> ![image](https://user-images.githubusercontent.com/30719670/273559653-c485be71-bb0b-425d-8539-dc342f6bffca.png)
> 
> This seems optimal, though user preference is somewhat ignored as it uses darker() three times

I would like to test this a bit when I get some time.. It might be sufficient to say that the color chosen by the user is darkened in dark mode. Or maybe we need the user to get other colors for the dark mode. Or, finally, maybe we should provide defaults that work for both modes, and allow the user to change them if they really want. (which would mean we need to use different internal config names or we'll pick what the user had chosen in the past)

2023-10-11 16:07 UTC, smallg0at commented
> > ![image](https://user-images.githubusercontent.com/30719670/273559653-c485be71-bb0b-425d-8539-dc342f6bffca.png)
> > This seems optimal, though user preference is somewhat ignored as it uses darker() three times.
> 
> I would like to test this a bit when I get some time. It might be sufficient to say that the color chosen by the user is darkened in dark mode. Or maybe we need the user to get other colors for the dark mode. Or, finally, maybe we should provide defaults that work for both modes and allow the user to change them if they really want. (which would mean we need to use different internal config names, or we'll pick what the user had chosen in the past)

- Allow user to get other colors exclusive for the dark mode is probably not a great idea, as edumips64 is not a software with a complete theme system that covers the entire UI (like VSCode). This would only bloat the setting page where the user will be needed to set the color twice.
- Dimming the color with `darker()` is possible but this specific method lacks detailed customization (no args). Two phases are a little too bright and three is a little to dark to be noticed.
- I'll try to find if one-color-fits-both solution is possible.

2023-10-13 06:51 UTC, smallg0at commented
![image](https://github.com/EduMIPS64/edumips64/assets/30719670/3eedf310-ce6e-46d2-86cf-c5065aa0a313)

Webapp is receiving an update as well

2023-10-13 08:28 UTC, lupino3 commented
> ![image](https://user-images.githubusercontent.com/30719670/274819277-3eedf310-ce6e-46d2-86cf-c5065aa0a313.png)
> 
> Webapp is receiving an update as well

Woah... THANK YOU!

2023-10-13 13:35 UTC, lupino3 commented
![image](https://github.com/EduMIPS64/edumips64/assets/200139/f2a43177-88d6-49dc-94e7-0e03446e24fd)

the new accordion-based interface makes SO MUCH MORE SENSE than what I quickly threw together.

Thank you, you are amazing!

2023-10-13 13:38 UTC, lupino3 commented
Small note: I think the bottom of the web UI is not visible anymore, the widgets seem to extend outside of the web browser view.

2023-10-13 13:39 UTC, smallg0at commented
# Finalizing Webapp

The development related to this webapp in the PR has concluded.

## Changes

- Redesigned UI placements, allowing this thing to at least look like an IDE
- Adds dark mode, which will always match system / browser preference on this. Not manually tunable.
- Now user is allowed to manually specify how many step to run in Multi-Step
- Version code gets moved to the Help dialog

2023-10-13 13:43 UTC, smallg0at commented
> Small note: I think the bottom of the web UI is not visible anymore, the widgets seem to extend outside of the web browser view.

I cannot replicate this issue so far, I might need a screenshot of it happening

2023-10-13 13:43 UTC, lupino3 commented
> # Finalizing Webapp
> The development related to this webapp in the PR has concluded.
> 
> ## Changes
> * Redesigned UI placements, allowing this thing to at least look like an IDE
> * Adds dark mode, which will always match system / browser preference on this. Not manually tunable.
> * Now user is allowed to manually specify how many step to run in Multi-Step
> * Version code gets moved to the Help dialog

Since this PR has both webapp and (incomplete) desktop changes, would you like to split out the webapp changes in a separate PR so I can merge it sooner?

2023-10-13 13:44 UTC, lupino3 commented
![image](https://github.com/EduMIPS64/edumips64/assets/200139/c12916f0-347a-4e1a-914d-e736d7fb00e4)

This is how it looks like if I go full-screen and then resize down.

2023-10-13 13:46 UTC, smallg0at commented
Fixed. Turns out flexGrow panics out and took an entire screen

2023-10-13 13:49 UTC, smallg0at commented
## Known Issue

- Due to the nature of EduMips64's logo, its contrasts are terrible in dark mode

2023-10-13 13:51 UTC, smallg0at commented
> ![image](https://user-images.githubusercontent.com/200139/274918584-c12916f0-347a-4e1a-914d-e736d7fb00e4.png)
> 
> This is how it looks like if I go full-screen and then resize down.

Overlooked the error counter component, going to look into it

2023-10-13 13:51 UTC, lupino3 commented
> ## Known Issue
> * Due to the nature of EduMips64's logo, its contrasts are terrible in dark mode

I was about to comment exactly about this :)

![image](https://github.com/EduMIPS64/edumips64/assets/200139/716638f7-fc19-4af0-acb1-1cff2a48f82a)

It's fine, just open an issue about it and we'll fix it later. This looks amazing, thank you!

2023-10-13 14:15 UTC, smallg0at commented
> > # Finalizing Webapp
> > The development related to this webapp in the PR has concluded.
> > ## Changes
> > 
> > * Redesigned UI placements, allowing this thing to at least look like an IDE
> > * Adds dark mode, which will always match system / browser preference on this. Not manually tunable.
> > * Now user is allowed to manually specify how many step to run in Multi-Step
> > * Version code gets moved to the Help dialog
> 
> Since this PR has both webapp and (incomplete) desktop changes, would you like to split out the webapp changes in a separate PR so I can merge it sooner?

Working on it, hope it won't blow up

2023-10-13 14:21 UTC, smallg0at commented
Webapp update is now #810

2023-10-15 15:40 UTC, smallg0at commented
@lupino3 Conclusion: one-color-for-all is not possible, will probably use current approach.

By the way, how can I reset those settings?

2023-10-16 15:57 UTC, lupino3 commented
It depends on the OS, I am not sure how to do it everywhere. See for example https://apple.stackexchange.com/questions/129489/how-do-i-delete-java-application-preferences

2023-10-18 04:07 UTC, smallg0at commented
@lupino3 This PR is ready to be merged

2023-10-18 08:50 UTC, lupino3 commented
Some initial feedback based on a quick test
<img width="2546" alt="image" src="https://github.com/EduMIPS64/edumips64/assets/200139/b250b430-5db8-45e7-a34d-b456d4e179a1">

First of all, this looks great, thank you! Love the new icons and overall the dark theme looks easier on the eyes.

1. The gray of the Cycles and Pipeline windows is different from the one in the other windows. I think it would make sense to centralize color management in a single class rather than instantiating colors throughout the code.
1. The white used in the GUICycles window is too bright, I think we need to make it darker in order to be easier on the eyes.
1. Same for the text in the Cycles and Pipeline window, it's far too bright, while the text in other windows is light grey so it's perfect.
1. Part of the Statistics window is still white, not sure why.
1. Shouldn't the colors in the Cycles/Pipeline window also get darker, like the ones in the other windows?

2023-10-18 08:54 UTC, lupino3 requested changes
Please apply those 2 small changes. Thanks!

2023-10-18 08:54 UTC, lupino3 commented on .github/workflows/ci.yml
Please revert changes on this file.

2023-10-18 08:54 UTC, lupino3 commented on src/main/java/org/edumips64/utils/CurrentLocale.java
> +    it.put("Config.DARKTHEME", "Dark theme (take effect after restart)");
```suggestion
    it.put("Config.DARKTHEME", "Tema scuro (applicato al prossimo avvio)");
```

2023-10-18 08:55 UTC, lupino3 commented
> Some initial feedback based on a quick test <img alt="image" width="2000" src="https://user-images.githubusercontent.com/200139/276178345-b250b430-5db8-45e7-a34d-b456d4e179a1.png">
> 
> First of all, this looks great, thank you! Love the new icons and overall the dark theme looks easier on the eyes.
> 
> 1. The gray of the Cycles and Pipeline windows is different from the one in the other windows. I think it would make sense to centralize color management in a single class rather than instantiating colors throughout the code.
> 2. The white used in the GUICycles window is too bright, I think we need to make it darker in order to be easier on the eyes.
> 3. Same for the text in the Cycles and Pipeline window, it's far too bright, while the text in other windows is light grey so it's perfect.
> 4. Part of the Statistics window is still white, not sure why.
> 5. Shouldn't the colors in the Cycles/Pipeline window also get darker, like the ones in the other windows?

Let me know if you have time to work on those changes, or if you'd rather merge the PR as-is (addressing the feedback I left in the review) and we can work on the remaining changes in another PR. Thanks!

2023-10-18 13:56 UTC, smallg0at commented
I have time working on this, so I'll resolve them in this PR.

> 1. The gray of the Cycles and Pipeline windows is different from the one in the other windows. I think it would make sense to centralize color management in a single class rather than instantiating colors throughout the code.

- [ ] Fix the color of the two panels. They currently use Color.Darkgrey and therefore can be customized to match theme.

> 2. The white used in the GUICycles window is too bright, I think we need to make it darker in order to be easier on the eyes.

- [ ] investigation planned

> 3. Same for the text in the Cycles and Pipeline window, it's far too bright, while the text in other windows is light grey so it's perfect.

- [ ] fixable, planned

> 4. Part of the Statistics window is still white, not sure why.

This was never experienced on my side. I assume that changing window size will fix this.

> 5. Shouldn't the colors in the Cycles/Pipeline window also get darker, like the ones in the other windows?

- [ ] investigation planned

2023-10-18 19:42 UTC, lupino3 commented
Thanks for the improvements! The only thing missing is the Statistics window being white for half:

<img width="846" alt="image" src="https://github.com/EduMIPS64/edumips64/assets/200139/c1a48716-fb39-4c08-8181-6a121dbcf724">

The behavior is clear when you make the window larger

<img width="1235" alt="image" src="https://github.com/EduMIPS64/edumips64/assets/200139/9aac746f-12e6-4654-be71-f564ba63d78a">

2023-10-19 00:07 UTC, smallg0at commented
> You may need to fix this here:
> 
> https://github.com/smallg0at/edumips64/blob/5254f01d6e4c976d41cda0ef92672d60a603ec28/src/main/java/org/edumips64/ui/swing/GUIStatistics.java#L70
> 
> Should be full-width, I think.

https://github.com/smallg0at/edumips64/blob/5254f01d6e4c976d41cda0ef92672d60a603ec28/src/main/java/org/edumips64/ui/swing/GUIStatistics.java#L68

It's this one's fault.

2023-10-19 01:42 UTC, smallg0at commented
![image](https://github.com/EduMIPS64/edumips64/assets/30719670/cdd8b4fb-1aef-4154-94e1-66c0e5cf5bc7)

Now the text has proper AA.

2023-10-19 05:53 UTC, smallg0at commented
The two ErrorDialog images uses Microsoft's COLRv1 Emoji, not sure if it will bring any licensing issue

2023-10-19 08:15 UTC, lupino3 commented on src/main/resources/images/error.png
Is there a reason why you are changing these 2 icons? We created them on purpose for EduMIPS64 and I'd like to keep them :)

2023-10-19 10:25 UTC, smallg0at commented on src/main/resources/images/error.png
The old icon does not suit the style of a modern UI, while looking messy when AA is applied. I'll bump up the resolution of the two images anyway, so I replaced them entirely.

So, what's the purpose, or what meanings are there in those icons?

2023-10-19 10:54 UTC, smallg0at commented on src/main/resources/images/error.png
btw, I saw a few unused images (errornn, error33, error4), I'm pretty curious what they are for.

2023-10-19 13:28 UTC, lupino3 commented on src/main/resources/images/error.png
it is mostly a historical artifact of the team that created EduMIPS64 :)
it's nothing important, but it's part of the "character" of the simulator. They are meant to be a funny way of delivering error messages to the user.

I'd love to maintain them, if possible.
The other, unused icons are other possible designs for the error/warning icons that have not been chosen.

2023-10-19 13:30 UTC, lupino3 commented on src/main/resources/images/error.png
one potential issue I see is that the error icon does contain a "death" reference in a Christian setting (the cross). I am not sure if that can be considered offensive to folks who don't appreciate this kind of references in a tool they are likely mandated to use for their studies.

2023-10-19 15:20 UTC, smallg0at commented on src/main/resources/images/error.png
Got it. Here's my decision:
- Rollback changes.
- Try to make the image less blurry / pixelated

2023-10-20 12:41 UTC, lupino3 commented
Do you want me to merge the changes as they are, or are you working on improving the existing icons? Thanks!

2023-10-20 13:32 UTC, smallg0at commented
> Do you want me to merge the changes as they are, or are you working on improving the existing icons? Thanks!

Currently working on the icon. This is a work-in-progress image with AI Upscaling.

![warning (1)](https://github.com/EduMIPS64/edumips64/assets/30719670/52800757-0b86-4a8c-8617-cc3b5683a047)

2023-10-20 14:37 UTC, smallg0at commented
Upscaled images, though ImageIcon is handled weirdly and decided to go 650\*500 -> **130\*100 -> 260\*200** (onscreen at 200% scale, which is made WITHOUT any AA mesaures)
![warning-hires](https://github.com/EduMIPS64/edumips64/assets/30719670/b5427394-f018-4d5d-ad19-5defcad60e27)
![error-hires](https://github.com/EduMIPS64/edumips64/assets/30719670/a9f2dce7-af56-4146-8d69-f36b7c60f630)

2023-10-21 16:31 UTC, merged